### PR TITLE
improve odk_client.md

### PR DESCRIPTION
**Pull request by Ndacyayisenga-droid**

### CODE REVIEW

**Comment by robsavoye** [comment]
There is no "list-projects", it's just "projects". You can execute /odkconvert/odk_client.py -h to get a list of all the options.

**Comment by Ndacyayisenga-droid** [comment]
> There is no "list-projects", it's just "projects". You can execute /odkconvert/odk_client.py -h to get a list of all the options.

done

**Comment by robsavoye** [comment]
For the delete options, please add a note that this only be used with great care. Unlike ODK Central, which merely archives projects, the deletion here removes it from the database completely, loosing all associated data. It's primarily a debugging and administrative tool that should rarely be used.

**Comment by Ndacyayisenga-droid** [comment]
> For the delete options, please add a note that this only be used with great care. Unlike ODK Central, which merely archives projects, the deletion here removes it from the database completely, loosing all associated data. It's primarily a debugging and administrative tool that should rarely be used.

Done

**Pull request closed without merging**
