### PR TITLE
Generate docs with mkdocs, remove wiki

### PR DESCRIPTION
**Pull request by spwoodcock**
# Problem

- Currently we have a `docs` directory that syncs to the Wiki.
- I think this needs a big overhaul.
- Github Wiki is ok for a small amount of long form documentation, but not very flexible.
- Github Wiki cannot easy host API docs.

# Solution

- Migrate everything to a custom documentation website, generated using mkdocs.
- This could house all existing manuals, plus API docs auto-generated with mkdocstrings-python.
- This PR contains the template, but the work of organising docs / fixing links / generating API doc pages would have to be done.

### CODE REVIEW

**Comment by robsavoye** [comment]
As we're now adding mkdocs comments in the code, wouldn't we want the generated API docs to also be on the wiki ? I'm not sure I see a reason to separate them.

**Comment by spwoodcock** [comment]
My thoughts were that the wiki was a place to describe the project, but Github Pages is the place for API docs.

- With Github Pages we would have a dedicated URL: https://hotosm.github.io/osm-fieldwork/ to view the docs.
- We could even add a DNS entry somewhere to redirect however we like: docs.hotosm.org/osm-fieldwork.
- We can style the docs however we like - with the HOT colour scheme etc (Pages is a lot more feature rich than Wiki).

It's quite easy to include all the content of wiki in the docs using symlinks, but not vice versa.

Let me know your thoughts 😄

**Comment by spwoodcock** [comment]
If we merge this PR, then the Pages should auto-deploy and you can see the difference / assess yourself which is better.

**Comment by robsavoye** [comment]
If I approve this PR, the existing wiki is unchanged, and there will also be a new one under github pages ?

**Comment by spwoodcock** [comment]
Yep exactly, it won't affect anything in the wiki.

**Pull request merged**
