### PR TITLE
Added packages python-calamine and xlsxwriter

### PR DESCRIPTION
**Pull request by Sujanadh**
## Updates
`python-calamine` and `xlsxwriter` are added as packages. These packages are required to be used as an engine with pandas for reading and writing `xlsx` files.

## What I encountered?
Got this dependency error from psycopg2 , I don't think it is related with these packages, I guess we can ignore it?
```
pdm.exceptions.BuildError: Build backend raised error: Showing the last 10 lines of the build output:
It appears you are missing some prerequisite to build the package from source.

You may install a binary package by installing 'psycopg2-binary' from PyPI.
If you want to install psycopg2 from source, please install the packages
required for the build and try again.
```

### CODE REVIEW

**Comment by spwoodcock** [comment]
Thanks Sujan!

You are right the psycopg error can ignored 👍
It's fixed by installing libpq

**Comment by Sujanadh** [comment]
## Updates:
- added `building_exists` condition (yes/no) , aborting survey form if it is equal to 'no'
- created a group to include every other survey questions in order to abort form based on `building_exists` value

**Comment by Sujanadh** [comment]
@spwoodcock it is good to merge, but a test with these changes would be appreciated.

**Comment by spwoodcock** [comment]
Will check and merge today!

**Comment by spwoodcock** [comment]
I updated to remove `xlsxwriter` and replace with `openpyxl` as we don't need the precise editing capability of `xlsxwriter` - sorry for the initial confusion on this.

However I kept `calamine` as the xlsx/xls reader, as it's a fantastic library:
- Extremely fast reading of large spreadsheets - not as useful for use, but still good.
- More importantly, support for a wide array of data formats, including **xls** which `openpyxl` does not support!

**Comment by spwoodcock** [comment]
I started writing a very basic test for this.

@Sujanadh could you possibly finish this off?
Perhaps it's best to test with a form other than the included `buildings.xls` as that already includes the mandatory fields!
(I just used it as an example)

**Comment by spwoodcock** [comment]
I made a few small changes!

Also added some tests - let me know if this works / you agree with the edits & I will merge 👍

**Comment by Sujanadh** [comment]
I tested it. it is good to go

**Pull request merged**
