### PR TITLE
Add documentation for OdkCentral.py

### PR DESCRIPTION
**Pull request by Ndacyayisenga-droid**

### CODE REVIEW

**Comment by robsavoye** [comment]
OdkCentral is the base class, usually only the derived classes are used. See central_crud.py in the FMTM repository. There is also some minimal test code on the bottom of OdkCentral.py. There is no get_metadata() method, nor delete_form. If you do 'grep def OdkCentral.py', it'll list all the methods in the file.

**Comment by Ndacyayisenga-droid** [comment]
> grep def OdkCentral.py

Oooops sorry about that. Don't know where I got `get_metadata()`😁. Thanks, Now I can see all the methods here without a hustle🙏. I tried to update the docs seeing through these methods. Let me know if I missed something 

```
mac@noah odkconvert % grep def OdkCentral.py
log_level = os.getenv("LOG_LEVEL", default="INFO")
    def __init__(self, url=None, user=None, passwd=None):
            url = os.getenv("ODK_CENTRAL_URL", default=None)
            user = os.getenv("ODK_CENTRAL_USER", default=None)
            passwd = os.getenv("ODK_CENTRAL_PASSWD", default=None)
        self.verify=os.getenv("ODK_CENTRAL_SECURE", default=True)
    def authenticate(self, url=None, user=None, passwd=None):
    def listProjects(self):
    def createProject(self, name=None):
    def deleteProject(self, project_id: int):
    def findProject(self, project_id=None, name=None):
    def findAppUser(self, user_id=None, name=None):
    def listUsers(self):
    def dump(self):
    def __init__(self, url=None, user=None, passwd=None):
    def getData(self, keyword):
    def listForms(self, id=None):
    def listAppUsers(self, projectId=None):
    def listAssignments(self, projectId=None):
    def getDetails(self, projectId=None):
    def dump(self):
    def __init__(self, url=None, user=None, passwd=None):
    def getName(self):
    def getFormId(self):
    def getDetails(self, projectId=None, xmlFormId=None):
    def listSubmissions(self, projectId, formId):
    def listAssignments(self, projectId=None, xmlFormId=None):
    def getSubmission(self, projectId=None, formId=None, disk=False):
    def getSubmissionMedia(self, projectId, formId):
    def addMedia(self, media=None, filespec=None):
    def addXMLForm(self, projectId=None, xmlFormId=None, xform=None):
    def listMedia(self, projectId=None, xmlFormId=None):
    def uploadMedia(self, projectId=None, xmlFormId=None, filespec=None):
    def getMedia(self, projectId=None, xmlFormId=None, filename=None):
    def createForm(self, projectId=None, xmlFormId=None, filespec=None, draft=None):
    def deleteForm(self, projectId=None, xmlFormId=None):
    def publishForm(self, projectId=None, xmlFormId=None):
    def dump(self):
    def __init__(self, url=None, user=None, passwd=None):
    def create(self, projectId=None, name=None):
    def delete(self, projectId=None, userId=None):
    def updateRole(self, projectId=None, xmlFormId=None, roleId=2, actorId=None):
    def grantAccess(
    def createQRCode(self, project_id=None, token=None, name=None):
```

**Comment by robsavoye** [comment]
Most of these methods also have a single line comment where they are defined that gives a brief summary of what it does.

**Comment by robsavoye** [comment]
The OdkCentral class is a base class, and not used directly. Only the derived classes are used.

**Comment by Ndacyayisenga-droid** [comment]
> The OdkCentral class is a base class, and not used directly. Only the derived classes are used.

How does that look like now?

**Comment by robsavoye** [comment]
There is no MyOdkCentral class, OdkCentral is a base class, and not used directly. The derived classes are:
class OdkProject(OdkCentral):
class OdkForm(OdkCentral):
class OdkAppUser(OdkCentral):

**Comment by Ndacyayisenga-droid** [comment]
> There is no MyOdkCentral class, OdkCentral is a base class, and not used directly. The derived classes are: class OdkProject(OdkCentral): class OdkForm(OdkCentral): class OdkAppUser(OdkCentral):

Does it look okay now?

**Comment by robsavoye** [comment]
Some of the class methods you document don't exist. Please reference the above list or the source file.

**Pull request closed without merging**
