### PR TITLE
improve basemapper.md docs with more examples

### PR DESCRIPTION
**Pull request by Ndacyayisenga-droid**
cc @rsavoye @petya-kangalova

### CODE REVIEW

**Comment by robsavoye** [comment]
Basemapper doesn't do the data conversion, it builds mbtiles and sqlitedb files of usually satellite imagery for ODK Collect and Osmand. It downloads map tiles to a cache, and then can use those to generate the basemap files. It doesn't deal with at all.

**Comment by Ndacyayisenga-droid** [comment]
@robsavoye how does this look now?

**Comment by spwoodcock** [comment]
This is a great addition @Ndacyayisenga-droid. My apologies, it seems that @Linda-Njau has a very similar PR that I ended up editing and merging, despite it coming after yours. We will work on merging the content of your basemapper.md into the current version.

**Comment by spwoodcock** [comment]
Hey @Ndacyayisenga-droid, thanks for help with the docs 😄 Please kindly refrain from using @ for everyone to review. We can see the PRs and will get around to merging when we have time.

**Comment by robsavoye** [comment]
Could please fix the conflicts ?

**Comment by Ndacyayisenga-droid** [comment]
> Could please fix the conflicts ?

Done

**Comment by spwoodcock** [comment]
The Installation section isn't necessary, but otherwise looks ok 👍

**Comment by Ndacyayisenga-droid** [comment]
Done

**Comment by robsavoye** [comment]
Have these changes been included in the other PR on this file ?

**Comment by Ndacyayisenga-droid** [comment]
> Have these changes been included in the other PR on this file ?

Somewhere some how, other PRs in the basemapper.md file are always merged before this😁 and this keeps this PR with conflicts. I will rebase the upstream and handle it with care to include my changes and this will help not to delete the merged changes of mohammed and submit another PR

**Comment by robsavoye** [comment]
Please clean up the conflicts and sync it up with other people's edits. Also this needs to be merged into the development branch, not main.

**Comment by Ndacyayisenga-droid** [comment]
> Please clean up the conflicts and sync it up with other people's edits. Also this needs to be merged into the development branch, not main.

resolved

**Pull request merged**
