### PR TITLE
Delete unused scripts and update the docs

### PR DESCRIPTION
**Pull request by rsavoye**
Now that *odk2osm.py* can process all three data formats from ODK, the older standalone scripts are buggy and incomplete, so deleted. The associated docs for these unused scripts have also been deleted. There were enough old and unused files to create confusion when trying to convert ODK data. The doc for *odk2osm.py* has also been updated to have real usage content.

### CODE REVIEW

**Comment by rsavoye** [comment]
Before this PR can be part of a new release, src/backend/app/central/central_crud.py in FMTM needs to have the call to CSVDump() replaced with the newer and more functional ODKParsers. Ath API is the same, so should be an easy change.

**Comment by spwoodcock** [comment]
There are merge conflicts apparently? 

Perhaps with the edit made to basemapper and sqlite

**Comment by rsavoye** [comment]
test_conflation can be deleted, as odk_merge.py has been replaced by conflator.

**Comment by rsavoye** [comment]
Probably the easy way to remove the conflict is to delete tests/test_conflation.py from main. It's deleted in the PR already.

**Pull request merged**
