### PR TITLE
Improve odk_merge.md

### PR DESCRIPTION
**Pull request by Ndacyayisenga-droid**

### CODE REVIEW

**Comment by robsavoye** [comment]
This PR needs to be applied to odkconvert, not FMTM.

**Comment by robsavoye** [comment]
The --boundary (-b) option only takes a GeoJson file containing, not bounding box coordinates. It'd be a nice enhancement to add support for that, but currently it doesn't exist.

**Comment by Ndacyayisenga-droid** [comment]
> The --boundary (-b) option only takes a GeoJson file containing, not bounding box coordinates. It'd be a nice enhancement to add support for that, but currently it doesn't exist.

Do you mean something like this

```
{
  "type": "Feature",
  "properties": {},
  "geometry": {
    "type": "Polygon",
    "coordinates": [
      [
        [lon1, lat1],
        [lon2, lat2],
        [lon3, lat3],
        [lon4, lat4],
        [lon1, lat1]
      ]
    ]
  }
}

```
Replace `lon1`, `lat1`, `lon2`, `lat2`, `lon3`, `lat3`, `lon4`, and `lat4` with the longitude and latitude coordinates of the four corners of your boundary polygon. Make sure the first and last `coordinates` in the coordinates array are the same (this will close the polygon).

1. Save the file with a `.geojson` extension (e.g. `boundary.geojson`).

2. Use the `-b` option with the path to your boundary GeoJSON file when running `odk_merge.py`

**Comment by robsavoye** [comment]
Usually the geojson file used for the boundary is created using ogr2ogr, QGIS, or Josm. Manually tediting it is uslayy a mistake.

**Comment by Ndacyayisenga-droid** [comment]
> Usually the geojson file used for the boundary is created using ogr2ogr, QGIS, or Josm. Manually tediting it is uslayy a mistake.

Done

**Comment by Ndacyayisenga-droid** [comment]
Resolved conflicts for this

**Pull request closed without merging**
